### ISSUE TITLE
refresh_tokens failure

### ISSUE THREAD

**Issue by chip-rosenthal** [yracine/device-type.myecobee#14]
I wanted to let you know that I installed an ecobee with this custom device type yesterday. (Thanks!) It was working fine. Now I'm getting errors from refresh_tokens, with a log message "need to re-login to ecobee".

The last successful operation I've got is:

2015-12-02 7:20:24.177 AM UTC poll>done for thermostatId =3...	

Next log entry:

2015-12-02 7:20:25.569 AM UTC refresh_tokens>exception groo...

Ecobee Thermostat verbose trace is refresh_tokens>exception groovyx.net.http.HttpResponseException: Unauthorized at https://api.ecobee.com/token?grant_type=refresh_token&amp;code=****&amp;client_id=****

(That failure would be 01:20 in my local timezone. I wasn't doing anything on the system at that time.)

There has not been a successful operation since this failure started.

I'll re-auth the device to clear this. But I wanted to share this report in case there might be an issue. Let me know if there is any info I can gather for you.

**Comment by allen00se** [comment]
I installed this yesterday and have been seeing the same error as well.

**Comment by yracine** [comment]
Please follow my recommendations under the ST community wiki (known issues) and
the troubleshooting section (item no 6) where the ecobee change is described.

http://thingsthataresmart.wiki/index.php?title=My_Ecobee_Device#Known_issues

**Comment by chip-rosenthal** [comment]
Thanks.

**Comment by jkeenest** [comment]
Is it possible to update it to refresh every 30 to 45 minutes?  It seems that doing so every 55 minutes means any failure will cause the exception to occur.  I get this pretty regularly even after re-authenticating.  My settings poll every 10 minutes.  I get these errors now several times a day typically and have to re-authenticate repeatedly.  Is anyone NOT getting these errors on a regular basis?

**Comment by jaypeecee** [comment]
I've set the polling to 30, even 45 minutes (1 ecobee3 and 3 x sensors) and
the token to renew automatically every 30 mins; still had issues.

**Comment by jkeenest** [comment]
Anyone having any better luck with the standard SmartThings Ecobee SmartApp?

**Comment by jaypeecee** [comment]
I've had the standard App running since Friday with no drops, but note that
feature which it's completely anemic/borderline useless compared to Yves'
device type. Also, no remote sensors in ST with the standard SmartApp :(

Stability and usability seem mutually exclusive, for the moment....

**Comment by snakedog116** [comment]
I get these errors multiple times a day as well, updated all of the device
types and smart apps. no luck.


Kristopher Dreger
780-909-5275

**Comment by yracine** [comment]
@jaypeecee, I have the stock ST device in parallel also. But, be aware: even if it looks like the stock ST device  is running (and does not throw exceptions), if you try to increase/decrease the setpoints or resumeProgram, you'll find out that it is not responsive to any commands and does not do anything at the physical thermostat.

**Comment by yracine** [comment]
Hi @jkeenest, the access token is already renewed every 35 minutes instead of every 55 minutes since  version 3.4.2 (BTW, the access token is only valid for 1 hour).

**Comment by jkeenest** [comment]
Hmmmm, have you tried pursuing this with Ecobee in their developer community?  I realize it is a timing issue on the ST side but what does Ecobee think about this?  Would they consider relaxing the refresh of every hour to maybe 2-3 hours?

**Comment by yracine** [comment]
Hi, the issue is not related to my code and ST seems to be working  on it as per this email that was forwarded  to me by a fellow community member:

*italic* 
While it may not be out for a few weeks it does look like we have some Ecobee integration improvements slated for later this month. That should hopefully get this Token issue cleaned up. There isn't a good solution for the short term, but lets see how the platform update later this month helps.

Riley,
SmartThings Support
*italic*

**Comment by yracine** [comment]
@jkeenest, I have been in contact with Ecobee for a while, and believe me, they will not change their security policies just for SmartThings..... They have many partners and it's a specific ST issue.

**Comment by jkeenest** [comment]
Excellent that you are on top of it and I appreciate all of the effort.  Your apps are far better than the out-of-the-box smart app.  Quick question.  You say you must uninstall all of the SmartApps after updating the code in the troubleshooting steps.  Is this necessary after any update or just the recent update?

**Comment by yracine** [comment]
@jkeenest, you need to uninstall only if you have not done it since December 1st. There were some ecobee API changes that day that broke the token renewal logic  as indicated here:

https://www.ecobee.com/home/developer/api/documentation/v1/change-log.shtml

Please refer to the ST community wiki for any known issues or troubleshooting:

http://thingsthataresmart.wiki/index.php?title=My_Ecobee_Device#Known_issues
Bye.

**Comment by alwineinger** [comment]
For what it's worth, I installed device and smartapp code from SANdood's fork earlier last week and have yet to experience token errors. I have three remote sensors I'm monitoring for temp and motion in addition to the main Ecobee3.

**Comment by yracine** [comment]
@jkeenest,

Till ST makes some changes to their cloud backend (Devconn) as promised, I will ask you to test a new version in my beta branch (if you're interested):

- So far, my code has been proactive in dealing with exceptions, but as ST cloud now seems to throw exceptions for  HTTP requests coming from some users (but, not all of them as I and others don't experience any exceptions since my last change on December 1st), I'm wondering if I've done some over-engineering on this issue.

- I created a new version of MyEcobeeDevice, myEcobeeInit and ecobee3RemoteSensorInit in my beta branch that deals differently with exceptions using a handleExceptionFlag.  The flag is set to false by default, and  in that case, the code in my smartapps will not handle the exceptions pro-actively and just try to proceed normally despite exceptions.

- Please give a try and let me know.  

https://github.com/yracine/device-type.myecobee/tree/beta

As I don't experience any exceptions myself, it's kind of difficult for me to find a workaround.

P.S. If you have uninstall & re-install MyEcobee Device, you just need to copy and paste the code,save &publish for the smartapps and MyEcobeeDevice.

**Comment by jkeenest** [comment]
I just re-installed the apps and device type yesterday with the latest and have not had any exceptions since then.  If I do, I will try this beta.  Thanks!

**Comment by yracine** [comment]
Hi,

According to some feedback from several users, my code is now working with the
workaround that I implemented about the connection issues.

My Ecobee Device, MyEcobeeInit, Ecobee3RemoteSensorInit need to be resync first at the main branch (just save & publish the code in the IDE).

https://github.com/yracine/device-type.myecobee

Regards.

P.S. My code now ignores some exceptions that are thrown by the ST cloud backend (i.e. groovyx.net.http.HttpResponseException ) for some users.

Please support the developer  :grinning:

**Comment by yracine** [comment]
Hi,

Good news: after a lot of investigation and some hard work, I found a permanent workaround to the connection issues between ST and ecobee.  

However, please take note of the following:

http://thingsthataresmart.wiki/index.php?title=My_Ecobee_Device#Notes_to_MyEcobee_Device_Users_-_Contribution_is_now_required

Regards.

P.S. If you want to take advantage of the new version (faster response times & no more exceptions), please send me a donation and you'll be part of the upgrade list.

:grinning:
