### ISSUE TITLE
java error messages when installing ecobee3RemoteSensor

### ISSUE THREAD

**Issue by EldRick** [yracine/device-type.myecobee#15]
My ecobee3 is communicating with the v2 ST hub, but when I execute the ecobee3RemoteSensorsInit, I get to the Which Thermostat panel and select mine, and then when I tap Next I see a white panel with a chaser for a second or two, then blank white, with Done at the top. If I tap Done, I get a red "Error - bad state. Unable to complete page configuration." I've waited a while to see if it ever gets the devices, but no luck. 
I see both motion detector and temperature settings published under My Device Types, I've cleared the app cache on the Sony phone (latest Lollipop). I've removed ecobee3RemoteSensorinit from the ST app and reinstalled it.
Live logging shows these errors:
   ---
f061d4a9-2c05-4ea7-a2d7-41b44b0d531a  6:26:03 PM: error java.lang.ArrayIndexOutOfBoundsException: 1 @ line 95
f061d4a9-2c05-4ea7-a2d7-41b44b0d531a  6:26:03 PM: debug selectMotionSensors>ecobeeSensors= [null]
0961175e-038d-4c40-bc11-4f602e87798c  6:26:03 PM: error java.lang.NumberFormatException: For input string: "unknown" @ line 3020
   ---
Help!
Rick Zehr
rwzehr@gmail.com

**Comment by yracine** [comment]
Hi,

1) First, check your thermostat firmware version, and make sure that your remote sensors are truly reporting at your physical thermostat as specified here:

http://thingsthataresmart.wiki/index.php?title=Ecobee3RemoteSensorInit#Troubleshooting

2) If you have the right firmware version,  then make sure that you have the latest version
of MyEcobeeDevice and ecobee3RemoteSensorInit at my github

3) Follow step 8 at the readme for enabling more tracing (see trace parameter).

https://github.com/yracine/device-type.myecobee/blob/master/README.md

3)  Activate Live Logging in the IDE, and execute ecobee3RemoteSensorInit

4) PM me the logs but only for MyEcobeeDevice (by filtering it at the top).

https://graph.api.smartthings.com/ide/logs

Regards.

**Comment by EldRick** [comment]
running 3.6.1 on the e3. sensors all present and functional. trace on.
———
0961175e-038d-4c40-bc11-4f602e87798c <https://graph.api.smartthings.com/ide/logs#0961175e-038d-4c40-bc11-4f602e87798c> 8:05:04 PM: error generateRemoteSensorEvents>>doRequest>exception groovyx.net.http.HttpResponseException: Internal Server Error for https://api.ecobee.com/1/thermostat?format=json&body=%7B%22selection%22%3A%7B%22selectionType%22%3A%22thermostats%22%2C%22selectionMatch%22%3A%22312930829973%22%2C%22includeSensors%22%3A%22true%22%7D%7D
0961175e-038d-4c40-bc11-4f602e87798c <https://graph.api.smartthings.com/ide/logs#0961175e-038d-4c40-bc11-4f602e87798c> 8:05:04 PM: debug doRequest>exception groovyx.net.http.HttpResponseException: Internal Server Error for https://api.ecobee.com/1/thermostat?format=json&body=%7B%22selection%22%3A%7B%22selectionType%22%3A%22thermostats%22%2C%22selectionMatch%22%3A%22312930829973%22%2C%22includeSensors%22%3A%22true%22%7D%7D
0961175e-038d-4c40-bc11-4f602e87798c <https://graph.api.smartthings.com/ide/logs#0961175e-038d-4c40-bc11-4f602e87798c> 8:05:04 PM: debug refresh_tokens> uri = https://api.ecobee.com/token?grant_type=refresh_token&code=tJDfVjbCDTtv20IluaXYGOc8u53BoNJo&client_id=null
0961175e-038d-4c40-bc11-4f602e87798c <https://graph.api.smartthings.com/ide/logs#0961175e-038d-4c40-bc11-4f602e87798c> 8:05:03 PM: debug refreshChildTokens>begin token auth= {"poll":{"last":1449374415359,"rescheduled":1449374436099},"authexptime":1449370794189,"tokenType":"Bearer","accessToken":"12b2f303-7083-4221-b062-220fe98a4137","oauthInitState":"477b6434-90fb-422c-bf36-98d373542d08","expiresIn":3599,"exceptionCount":10,"authToken":"Uc8gadW15hSlVGoo2r9yoPOxAlIvMHzI","refreshToken":"tJDfVjbCDTtv20IluaXYGOc8u53BoNJo","oauthTokenProvided":true,"msg":null}
0961175e-038d-4c40-bc11-4f602e87798c <https://graph.api.smartthings.com/ide/logs#0961175e-038d-4c40-bc11-4f602e87798c> 8:05:03 PM: debug login> about to call refreshThisChildAuthTokens
0961175e-038d-4c40-bc11-4f602e87798c <https://graph.api.smartthings.com/ide/logs#0961175e-038d-4c40-bc11-4f602e87798c> 8:05:03 PM: debug doRequest> get> uri https://api.ecobee.com/1/thermostat?format=json&body=%7B%22selection%22%3A%7B%22selectionType%22%3A%22thermostats%22%2C%22selectionMatch%22%3A%22312930829973%22%2C%22includeSensors%22%3A%22true%22%7D%7D, args= %7B%22selection%22%3A%7B%22selectionType%22%3A%22thermostats%22%2C%22selectionMatch%22%3A%22312930829973%22%2C%22includeSensors%22%3A%22true%22%7D%7D
0961175e-038d-4c40-bc11-4f602e87798c <https://graph.api.smartthings.com/ide/logs#0961175e-038d-4c40-bc11-4f602e87798c> 8:05:03 PM: debug api> about to call doRequest with (unencoded) args = {"selection":{"selectionType":"thermostats","selectionMatch":"312930829973","includeSensors":"true"}}
0961175e-038d-4c40-bc11-4f602e87798c <https://graph.api.smartthings.com/ide/logs#0961175e-038d-4c40-bc11-4f602e87798c> 8:05:03 PM: debug isTokenExpired> check expires_in: 1449370794189 > time check for exp: 1449376203239
0961175e-038d-4c40-bc11-4f602e87798c <https://graph.api.smartthings.com/ide/logs#0961175e-038d-4c40-bc11-4f602e87798c> 8:05:03 PM: debug getRemoteSensorUpdate> about to call api with body = {"selection":{"selectionType":"thermostats","selectionMatch":"312930829973","includeSensors":"true"}} for thermostatId = 312930829973...
0961175e-038d-4c40-bc11-4f602e87798c <https://graph.api.smartthings.com/ide/logs#0961175e-038d-4c40-bc11-4f602e87798c> 8:05:03 PM: debug determine_tstat_id> tstatId = 312930829973
0961175e-038d-4c40-bc11-4f602e87798c <https://graph.api.smartthings.com/ide/logs#0961175e-038d-4c40-bc11-4f602e87798c> 8:05:04 PM: debug refresh_tokens>exception groovyx.net.http.HttpResponseException: Unauthorized at https://api.ecobee.com/token?grant_type=refresh_token&code=tJDfVjbCDTtv20IluaXYGOc8u53BoNJo&client_id=null
0961175e-038d-4c40-bc11-4f602e87798c <https://graph.api.smartthings.com/ide/logs#0961175e-038d-4c40-bc11-4f602e87798c> 8:05:03 PM: debug isTokenExpired> check expires_in: 1449370794189 > time check for exp: 1449376203956
0961175e-038d-4c40-bc11-4f602e87798c <https://graph.api.smartthings.com/ide/logs#0961175e-038d-4c40-bc11-4f602e87798c> 8:05:03 PM: debug refreshChildTokens>end data.auth=[ecobeeType:registered, scope:null, authexptime:1449370794189, thermostatId:312930829973, expires_in:3599, token_type:Bearer, refresh_token:tJDfVjbCDTtv20IluaXYGOc8u53BoNJo, access_token:Uc8gadW15hSlVGoo2r9yoPOxAlIvMHzI, appKey:qqwy6qo0c2lhTZGytelkQ5o8vlHgRsrO]
0961175e-038d-4c40-bc11-4f602e87798c <https://graph.api.smartthings.com/ide/logs#0961175e-038d-4c40-bc11-4f602e87798c> 8:05:03 PM: debug getRemoteSensorUpdate> about to call build_body_request for thermostatId = 312930829973…
-----------------

Regards,
Rick

**Comment by yracine** [comment]
Hello,

You need to authenticate at ecobee as seen here:

groovyx.net.http.HttpResponseException: Unauthorized at https://api.ecobee.com/token?grant_type=refresh_token&code=tJDfVjbCDTtv20IluaXYGOc8u53BoNJo&client_id=null
0961175e-038d-4c40-bc11-4f602e87798c <https://graph.api.smartthings.com/ide/logs#0961175e-038d-4c40-bc11-4f602e87798c> 8:05:03 PM: debug isTokenExpired> check expires_in: 1449370794189 > time check for exp: 1449376203956

1) Please run MyEcobeeInit and restart over.

2) If you have recurrent unauthorized exceptions, please look at MyEcobee device's known issues at

http://thingsthataresmart.wiki/index.php?title=My_Ecobee_Device#Known_issues

Regards.

**Comment by EldRick** [comment]
That is very curious, as I go to the My Apps page on the Ecobee site, and it shows 


ecobee IFTTT Channel
SmartThings
Add Application
You have added the following application that can access your ecobee


SmartThings
Developed by SmartThings
Phone 612-386-9382
Email scott@smartthings.com
Website http://smartthings.com/
Integrate ecobee thermostats with SmartThings

This application has the following permissions:
	• View and change data and settings on your ecobee thermostat(s)
	• View and change data and settings on your EMS thermostat(s) based on your user access privileges.

I’ve rerun the myEcobeeInit a dozen times. It authorizes me at the ecobee end.

Regards,
Rick

**Comment by yracine** [comment]
Yes, but as specified in the Know issues section of the ST community wiki, based on your logs, it seems that MyEcobee device lost its access token due to some connection issues.

Please look at my recommendations. 

At this point, I don't know how many ecobee3 thermostats and remote sensors you have, but be aware that there are some constraints due to ST platform limitations.

**Comment by EldRick** [comment]
It’s just one thermostat with 8 sensors. I saw the bit about instances for the sensors, but I’m apparently not even able to control the ecobee at this point, although I can see the device. I’ll ask them to update it, and perhaps that will make the difference.

**Comment by EldRick** [comment]
I finally uninstalled everything and removed all the app data, reinstalled the ST app, and all the ecobee stuff. Don’t know what I did wrong the first time, but this time, it all works.
Sorry for wasting your time earlier.

Regards,
Rick Zehr

**Comment by yracine** [comment]
No problem, please support the developer with a donation

**Comment by EldRick** [comment]
Will do.

**Comment by yracine** [comment]
Hi,

The connection issues can only be fixed by ST as those are cloud-to-cloud connectivity issues.

All I can do on my end is  to implement some throttling to avoid the connection issues as much as possible.

FYI, somebody forwarded me an email he got from ST support about our the ST-ecobee connection issues:

*While it may not be out for a few weeks it does look like we have some Ecobee integration improvements slated for later this month. That should hopefully get this Token issue cleaned up. There isn't a good solution for the short term, but lets see how the platform update later this month helps.*

*Riley,*

*SmartThings Support*


And, this is a reply from Tim Slagle from ST after I complained about the connection issues:

Continuing the discussion from [Initial Setup for Ecobee3, Smart-SI, EMS, Smart-02 thermostats - My custom Ecobee Device](https://community.smartthings.com/t/initial-setup-for-ecobee3-smart-si-ems-smart-02-thermostats-my-custom-ecobee-device/17260/115):

[quote="slagle, post:115, topic:17260, full:true"]
We are working on improving our end of Cloud and Lan connected devices. We can only control what we can control. 

Aside from that, the only recommendation I can recommend is to reduce polling intervals. This will rule out your connection being limited by the external API. I know MyQ and Ecobee are very specific about their polling intervals. I have read on their forums they recommend not polling more than every 30 seconds (maybe 10 seconds? I found both numbers but 30 second intervals show up more). 

I'd find it unlikely that you are hitting this limit, but I have also read on their forums something along the lines of "Our servers ensure that your thermostat is protected from attacks against it." I wonder if you are hitting that "wall" so to speak.

I say all this not to say it isn't on our end at all, but it may not be all on our end. Try reducing polling intervals and see if that resolves these timeout connection issues. :smile: I'd be interested to know. Maybe start by doubling your currently polling intervals.

Most of the other threads @yvesracine mentioned (with the exception of MyQ) are not related to this and are either related to a platform outage or DHCP issues. (We have a fix for wemo coming out in a little while that allows us to see and change the IP when the wemo Ip changes locally)
[/quote]

**Comment by yracine** [comment]
Hi,

According to some feedback from several users, my code is now working with the
workaround that I implemented about the connection issues.

My Ecobee Device, MyEcobeeInit, Ecobee3RemoteSensorInit need to be resync first at the main branch (just save & publish the code in the IDE).

https://github.com/yracine/device-type.myecobee

Regards.

P.S. My code now ignores some exceptions that are thrown by the ST cloud backend (i.e. groovyx.net.http.HttpResponseException ) for some users.

Please support the developer  :grinning:

**Comment by yracine** [comment]
Hi,

Good news: after a lot of investigation and some hard work, I found a permanent workaround to the connection issues between ST and ecobee.  

However, please take note of the following:

http://thingsthataresmart.wiki/index.php?title=My_Ecobee_Device#Notes_to_MyEcobee_Device_Users_-_Contribution_is_now_required

Regards.

P.S. If you want to take advantage of the new version (faster response times & no more exceptions), please send me a donation and you'll be part of the upgrade list.

:grinning:
