### ISSUE TITLE
blank screen

### ISSUE THREAD

**Issue by jckickflip** [yracine/device-type.myecobee#21]
when I start the app it comes up with the correct screen asking me to pick my themostat and I do then when I click next it just comes up with a blank screen. on my log I get

"c479fb25-52e3-487b-86e6-0aae813ae095  9:39:01 PM: debug selectEcobeeSensors>exception java.lang.IllegalArgumentException: Command 'generateRemoteSensorEvents' is not supported by device 7b66613b-7b51-4ca0-a05b-fadb87a45a9c of type 'Ecobee Thermostat'. Supported commands: [refresh, setHeatingSetpoint, setCoolingSetpoint, off, heat, emergencyHeat, cool, setThermostatMode, fanOn, fanAuto, fanCirculate, setThermostatFanMode, auto, setSchedule, ping, generateEvent, raiseSetpoint, lowerSetpoint, resumeProgram, switchMode, switchFanMode] when getting list of Remote Sensors, exiting..."

I have cleared cache nothing changes

**Comment by jckickflip** [comment]
ok I was able to get further by finding source code for 3.1.6 but still not working and it says to use version 3.6 atleast and I dont see that in the files downloaded from buying this

**Comment by yracine** [comment]
Hi, 

This smartapp has been thoroughly tested, and you're the only one with this issue.

Your issue is due to the following: you're trying to use ecobee3RemoteSensorInit with the wrong Device Type Handler (ecobee instead of My Ecobee device).  If you have any other issues, please send an email to services@maisonsecomatiq.com as I'm not using github so much. Please also include a detailed log using Live Logging.  Set the detailedNotif to true and LogFilter to 4.

Regards.
